services:
  frontend_server:
    image: test_frontend
    build:
      context: ./frontend
    container_name: frontend

  backend_server:
    image: test_backend
    build: ./backend
    container_name: backend
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: mysql

  reverse_proxy:
    image: nginx
    depends_on:
      - backend_server
      - frontend_server

volumes:
  mysql_data:
